#!/bin/sh
### BEGIN INIT INFO
# Provides:          red5sip
# Required-Start:    networking
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
set -e
DESC="Red5Sip bridge"
NAME=red5sip
USER=nobody
RED5SIP_HOME=/opt/red5sip
DAEMON=$RED5SIP_HOME/$NAME.sh
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

#
# Function that starts the daemon/service.
#
d_start() {
	# Check log file permissions
	sudo -u $USER -H sh -c "if !([ -w '$RED5SIP_HOME/log' ]); then echo 'Logs directory is not writable'; exit 1; fi"
	if [ -f $PIDFILE ]
	then
		echo "$NAME is already started\n"
	else
		start-stop-daemon --start -c $USER --pidfile $PIDFILE --chdir $RED5SIP_HOME --background --make-pidfile --exec $DAEMON
	fi
}
#
# Function that stops the daemon/service.
#
d_stop() {
	if [ -f $PIDFILE ]
	then
		start-stop-daemon --stop --quiet --pidfile $PIDFILE --name java
		rm -f $PIDFILE
	else
		echo "$NAME is not started\n"
	fi
}

#
# Function that checks the demon/service status
#
d_check_status() {
	if [ -f $PIDFILE ]
	then
		echo "$NAME is started\n"
	else
		echo "$NAME is not started\n"
	fi
}

case "$1" in
	status)
		d_check_status
	;;
	start)
		echo -n "Starting $DESC: $NAME\n"
		d_start
	;;
	stop)
		echo -n "Stopping $DESC: $NAME\n"
		d_stop
	;;
	restart|force-reload)
		echo -n "Restarting $DESC: $NAME\n"
		d_stop
		sleep 1
		d_start
	;;
	*)
		echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
		exit 1
	;;
esac
exit 0

